Try another way

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -121,8 +121,12 @@ jobs:
           git fetch origin ${{ steps.get_branch.outputs.branch_name }}
           git checkout master
           git checkout ${{ steps.get_branch.outputs.branch_name }}
-          full_output=$(git diff master..${{ steps.get_branch.outputs.branch_name }} | diff-test-coverage --diff-filter '*.java' '*.kt' '*.scala' '*.py' -c **/target/site/jacoco/jacoco.xml -t jacoco --)
-          echo "COVERAGE=$?" >> $GITHUB_ENV
+          full_output=$(git diff master..${{ steps.get_branch.outputs.branch_name }} | diff-test-coverage --diff-filter '*.java' '*.kt' '*.scala' '*.py' -c **/target/site/jacoco/jacoco.xml -t jacoco -- || true)
+          if echo "full_output" | grep -q 'ERROR:'; then
+            echo "COVERAGE=1" >> $GITHUB_ENV
+          else
+            echo "COVERAGE=0" >> $GITHUB_ENV
+          fi
           echo "COVERAGE_OUTPUT=$full_output" >> $GITHUB_ENV
           echo "Coverage output"
           echo $full_output
